### ISSUE TITLE
Sync acf fields with events

### ISSUE THREAD

**Issue by em-piguet** [christianwach/civicrm-acf-integration#1]
Hi, hope you are well !

I cannot find a way to sync custom fields in CIVIEVENT.

I have installed ACFPRO + Event Organiser + CIVICRM Event Organiser and the date or the location are correctly synced in both way.

but can't understand how the CIVICRM custom fields are linked to the ACF field "event" post type.. 

Thx

**Comment by christianwach** [comment]
@em-piguet Not quite sure what you're missing but it's exactly the same procedure as setting up Contact-to-Post sync:

My CiviCRM Custom Fields on a CiviEvent:
<img width="920" alt="Screen Shot 2020-03-28 at 16 17 38" src="https://user-images.githubusercontent.com/726936/77827862-fc537f00-710f-11ea-94cd-d2a486758bc8.png">

My ACF Custom Fields on an EO Event:
<img width="963" alt="Screen Shot 2020-03-28 at 16 17 22" src="https://user-images.githubusercontent.com/726936/77827860-fb225200-710f-11ea-9c6e-e8b15999a8c2.png">

The linkage in my ACF Field Group:
<img width="961" alt="Screen Shot 2020-03-28 at 16 18 11" src="https://user-images.githubusercontent.com/726936/77827863-fcec1580-710f-11ea-999d-cc3fb14a9d3e.png">

The linkages in my ACF Field settings:
<img width="961" alt="Screen Shot 2020-03-28 at 16 18 51" src="https://user-images.githubusercontent.com/726936/77827865-fe1d4280-710f-11ea-86a2-5d07d183acab.png">
<img width="964" alt="Screen Shot 2020-03-28 at 16 18 35" src="https://user-images.githubusercontent.com/726936/77827864-fd84ac00-710f-11ea-843a-37989ad09dbc.png">

Hope that helps.

**Comment by cfab** [comment]
Hello Christian, 
Hope you are fine… 
We don't have the last option you are showing in the image for  "The linkages in my ACF Field settings: »
So I made a fresh install of Wordpress and CiviCRM and same, this option is not showing. 
I thought it was maybe because of the language so I reverted language of both Wordpress and Civi to the default English version. 
But still the CiviCRM field options to make the link between the ACF field and the custom Civi field is not there. 
Am we missing something ? 
We use "Local by Flywheel" (old version) for local development but I can’t imagine that this affects you plugin. 
Do your plugin needs some specific settings for the DB or PHP (here are my current settings for this brand new fresh test instance ;-)
See you, 
Fabrice

**Comment by christianwach** [comment]
> We don't have the last option you are showing in the image for  "The linkages in my ACF Field settings:"

@cfab Have you saved the Field Group?

**Comment by cfab** [comment]
Yes of course…

**Comment by christianwach** [comment]
Can you confirm (with screenshots) that you have the CiviCRM and WordPress properly configured? It's hard to tell what your settings are. Without revealing sensitive information of course!

**Comment by cfab** [comment]
I made you a video ;-)

https://www.loom.com/share/b82497ea55a5438285cb34597e9f2cbc <https://www.loom.com/share/b82497ea55a5438285cb34597e9f2cbc>

**Comment by em-piguet** [comment]
when the plugin is activated, i get these new ACF fields (in red)
![Capture d’écran 2020-03-30 à 20 43 46](https://user-images.githubusercontent.com/1035240/77949519-61050a00-72c7-11ea-92a2-3b2c48552a6e.png)

**Comment by cfab** [comment]
Arrête ! Je lui carrément fait une vidéo - il m’a demandé des screnshots - ds laquelle je lui ai tout montré…

**Comment by christianwach** [comment]
@cfab Hmm, that's odd. Can you confirm that you have the latest CiviCRM Events Organiser plugin - i.e. version 0.5 (or 0.5.1)?

**Comment by christianwach** [comment]
@em-piguet That's good. Those are for specific kinds of sync, where ACF doesn't have a field that corresponds to one provided by CiviCRM.

**Comment by christianwach** [comment]
@cfab I wonder if your user has the right permissions? Here is my view of the CiviCRM Events list:

<img width="1256" alt="Screen Shot 2020-03-31 at 10 10 55" src="https://user-images.githubusercontent.com/726936/78008805-0657c680-7338-11ea-8729-53ad668aaadb.png">

Note that I have four options on the right of the screen, whereas you only have "Configure". CiviCRM ACF Integration respects permissions on both sides (i.e. in Event Organiser and CiviCRM) so perhaps you need to dig into those to see if something is missing?

Edit: sorry, we were on different screens 🤦‍♂ But still worth checking.

**Comment by cfab** [comment]
This was it ! Sorry for the trouble. I updated and I can see the field now.
Shame on me...

**Comment by em-piguet** [comment]
Updating to CiviCRM Event Organiser to 0.5.1 was the good answer. Thank you.

**Comment by christianwach** [comment]
@cfab Aha, good news! Enjoy your sync... 🎂
