### ISSUE TITLE
Unable to save synced contact type in Civi

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-acf-integration#10]
I have setup a contact type to CPT sync. When I go to save the the name or any related info on the civi contact, it fails.

```
Network Error
Unable to reach the server. Please refresh this page in your browser and try again.
```
On multisite, can this be replicated? How is this supposed to work with MS? I only activated on top level domain id 1.

**Comment by christianwach** [comment]
@andyburnsco C'mon Andy, you've got to give me more to go on :-) For example:

1. Steps to replicate.
2. Error log excerpt.
3. Versions on WordPress, CiviCRM, ACF and this plugin.

> How is this supposed to work with MS?

Sync should only happen on the site on which the change takes place. So, if you change a Contact's info on Site 1, the sync will happen only to the CPT on Site 1 and vice versa. Changes do not propagate to CPTs on other sites.

**Comment by andyburnsco** [comment]
I know...It was a rough day yesterday, I planned on circling back soon, I promise :)  

Thanks, I wanted to gather at least some basic info on how it *should work* on MS.

**Comment by christianwach** [comment]
Closing because I am archiving this repo in favour of [CiviCRM Profile Sync](https://github.com/christianwach/civicrm-wp-profile-sync).
