### ISSUE TITLE
Contact Sync stopped working

### ISSUE THREAD

**Issue by kurund** [christianwach/civicrm-acf-integration#11]
Here is the setup
* Created new post type 'Trainer'  and linked with CiviCRM contact sub type 'Trainer'

When a new contact of type 'Trainer' is added then new post was created in the WordPress.

10 posts were created correctly in WordPress and then it stopped working.

Any help is appreciated.

**Comment by christianwach** [comment]
Sorry @kurund but you haven't provided enough information for me to help you. Have you tried debugging to see what's going on?

**Comment by kurund** [comment]
@christianwach I did notice few errors while adding trainer and debugged it further to realize that the content type 'trainer' was not found.

On rechecking WP content type found that slug was changed to 'trainers' from 'trainer'. Hence, I had to remap the contact type with this content type. Now it is working as expected.

Sorry for the false alarm. I am closing the issue.
