### ISSUE TITLE
Compatibility beyond ACF ? 

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#2]
Hi,

I just discovered your plug-in an wonder if it may work with beyond ACF.

Sticking with custom field, the question could be  if it may work with field created manually ? or with a different custom field plug-in ?  and more specifically with pods ?
It seems to be designed for ACF only, but there may be some reasonably stable and easy way to open it ?

Broadening the question to custom post types, would it work if they are created manually ? or with the popular custom post type ui plug-in ? and with the less popular pods plug-in ? 

Thank's

**Comment by christianwach** [comment]
@jbonlinea 

1. No, this plugin won't work with Pods. It uses hooks provided by ACF to sync data _to_ CiviCRM and ACF functions to populate fields with data _from_ CiviCRM.
2. It doesn't matter how you create your Custom Post Types.

**Comment by jbonlinea** [comment]
Hi, 

Ok 

Thank's for your reply !

**Comment by jbonlinea** [comment]
Hi,

A small post to let you know that I did a successful try to combine Pods, ACF, this plug-in and CiviCRM !

Basically I create my post type with Pods, add some custom field with ACF and sync it with  thank's to your plug in into CiviCRM and back !
It work's like a charm !

I use pods for two reasons :

First, I like its templates feature and I can use it, along with pods shortcode, to display any custom fields, could they be created with both Pods or ACF.

Then pods is offer many-to-many relationship, so I use Pods custom field for my many-to-many needs, and ACF for my the field I want to sync with CiviCRM !!!

Combining theses plug-in is so empowering ! 
And this is probably one of the best walkaround I could think of regarding CiviCRM unability to display two shortcodes on the same page... 

just set it up, sync it, display it with pods template or real template for heavy tuning ! 

Thank's this is awesome !

**Comment by christianwach** [comment]
@jbonlinea You're welcome! Why not leave a message for the Drupal devotees on the Mattermost thread you started saying what you've done :-)

Scratch that - I see you already have!

**Comment by jbonlinea** [comment]
> @jbonlinea You're welcome! Why not leave a message for the Drupal devotees on the Mattermost thread you started saying what you've done :-)

I just did ;)

And someone has also suggested an alternative https://github.com/agileware/content-views-civicrm-data-processor ; but civicrm data processor install fails at the moment

**Comment by agileware-justin** [comment]
@jbonlinea @christianwach this is really good news and a very useful tool for WordPress & CiviCRM sites. Well done both of you :)

The Content Views integration with CiviCRM solves different problems and is really useful when you use the CiviCRM Data Processor to do the heavy lifting. eg. Browsable listings and summaries of CiviCRM data.

Thought you both might be interested in this other plugin we've been working on as it's just another tool to make CiviCRM integration with Wordpress easier. See https://github.com/agileware/wp-civicrm-ux/blob/master/USAGE.md
