### ISSUE TITLE
Sync CiviCRM-contact-types with WP-taxonomies rather than WP-custom-post-types :)

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#6]
Hi @christianwach 

#### details
Working and thinking on site structure, I think I have a use case where it would be relevent to sync CiviCRM contact with a custom taxonomy rather than a custom post type ?!

As taxonomies deals with custom field the same way as post types do, it seems your plug-in might embrace that and taxonomies could use you custom field type as well ? 

This would actually be awesome ! 

#### use case : 

take a conference, with panel and communications being two CPT; 
both panels an communication have authors, 
i can create a CPT for authors and a bidirectional relationship  field for panel and one for communications, 
I can display both CPT panel and comunication on the same wp-query,
 but I can't create a front end filter to filter them by author, as this filter would involve two custom field of two cpt

if author was a taxonomy, I could super easily do that

the underlying idea it that author are synced to civicrm contact ; on Civicrm side wether author is a taxonomy or a post type no not matter, but on the wp side yes,

**Comment by christianwach** [comment]
@jbonlinea I appreciate the suggestion, but this isn't likely to happen since it would require a complete rebuild!

You could, however, look at the CiviCRM Groups <--> WordPress Terms sync in version 0.7 (the latest) since this might help achieve what you're after.

**Comment by jbonlinea** [comment]
Hi :)

complete rebuilt, ouch, okay :)

At the moment I'm not sure how can the  CiviCRM Groups <--> WordPress Terms sync might help me to fulfill my need as I inted to create a relation between a single author (or contact) and its productions, that me be of different CPT.

but, there is a Great news
using [shadow](https://github.com/mrbobbybryant/shadow-taxonomy) taxonomies, I can turn any CPT into a taxonomy.

Now I have three CPT, author, panel, and communication, as weel as a shadow taxonomy, auhtor-tax.
And instead of creating bidirectional relationship betwen author and panel and author and communication, I do asign a author-tax term to my post.
I can thus filter my panels and communication through a my author-tax taxonomy, the late actually sunced with the author CPT itself syncet wi CiviCRM contact ! 

yay !


I guess for super heavy site with tens of thousands  of contact this might be a way too resource thirsty approach, but if contacts remains in in the hundreds or few thousands number it might be good enough !!!

Cheers and thank's again for your plug-in that is really a game changer when one want's to integrate civi and wp !

**Comment by jbonlinea** [comment]
> @jbonlinea I appreciate the suggestion, but this isn't likely to happen since it would require a complete rebuild!
> 
> You could, however, look at the CiviCRM Groups <--> WordPress Terms sync in version 0.7 (the latest) since this might help achieve what you're after.

Hi there, 

stupid question here :) 

where do I  sync CiviCRM Groups <--> WordPress Terms ? I can't fins anything in Civi group settings (accessed from here wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fgroup&reset=1), nor in wp tax, and I don't really get how could I do something by adding custom field to a taxonomy, if it the syns isn't alst set on civi side ? 

Any guidance would be welcome :)
Thank's

**Comment by christianwach** [comment]
> where do I sync CiviCRM Groups <--> WordPress Terms ?

The sync between CiviCRM Groups and WordPress Terms is defined on the Custom Taxonomy screens for every Post Type that is synced to a Contact.

Below is a screenshot that may help. The Students CPT is synced to a Contact Type and has two Custom Taxonomies (one hierarchical, one not) which apply to it. The option to connect a Term with a Group is shown:

<img width="609" alt="Screen Shot 2020-10-22 at 18 41 36" src="https://user-images.githubusercontent.com/726936/96909811-75446a80-1496-11eb-8a9d-90959997c14a.png">

There is no sync between ACF Fields attached to the Taxonomy and CiviCRM - it is a means by which synced Contacts can be "grouped" in WordPress via Terms.

**Comment by jbonlinea** [comment]
> > where do I sync CiviCRM Groups <--> WordPress Terms ?
> 
> The sync between CiviCRM Groups and WordPress Terms is defined on the Custom Taxonomy screens for every Post Type that is synced to a Contact.
> 

Ho, Ok,
My synced post types had no taxonomy, so I obviously couldn't see that !
It's cristal clear now ! 



> 
> There is no sync between ACF Fields attached to the Taxonomy and CiviCRM - it is a means by which synced Contacts can be "grouped" in WordPress via Terms.

Yep, this is what I understood when looking into ACF ! 

---

Big thank's for this awesome plugin and support

**Comment by christianwach** [comment]
Closing because I am archiving this repo in favour of [CiviCRM Profile Sync](https://github.com/christianwach/civicrm-wp-profile-sync).
