### ISSUE TITLE
Sync with already registered fields ?

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#7]
Hi @christianwach 

I wonder wether it may be possible to map and sync CiviCRM contact field to wp CPT fields that are not registered using ACF ? (it do not have to be from the ui)

---

Behind this question it question  the possibility to integrate civicr-acg-integration with other wp plug-in and provide a use case and workaround to illustrate where the idea stem from and where it goes

You might have head about  [co-author-plus](https://wordpress.org/plugins/co-authors-plus/)
It enable to assign "co-authors" to a wp post or CPT ; theses "co authors" could either be "native wp user" or "guest author", the later being a CTP.
There is a whole machinery to attribute co authors to a post from the wp UI, and it obviously uses the guest_author fields.

As with any CPT, I may add custom field to guest_author and sync them with CivCRM, 

But co author plus (the plugin) do not know about theses field and won't be able to uses them... obviously, thus I have two options : 

- sync / map civicrm contact field with a field registered by co author plus
- create guest_author ACF field for First name, last name, email, etc... guest_author already have fields for this type of content, yet I can sync them with their ACF counterparts (write a function that is triggered on post update and copy field XX value into field YY)

how do you see that ? the first solution seems more elegant than the other, but maybe less robust since subject to failure on one or the other plug-in update

**Comment by christianwach** [comment]
@jbonlinea Thanks for the suggestion.

**Comment by danaskallman** [comment]
@jbonlinea Are aware of any funding for something like this? I ask, as then more time could be allocated to these type of feature requests.

**Comment by jbonlinea** [comment]
Hi

I'm aware that open source do mean free to use but not free to create, maintain or enhance.
The project I'm busy with do heavily rely on open source  code, and could simply not exist without it. 
As such, I realistically do not expect heavy development nor custom development for free, nevertheless I belive that is it is often a tiny functionality, or that a single hook can be game changer in some uses case, and they might well already exist but not documented.
This said, I do take into account this problematic, and seriously consider supporting one or an other project, event if my contribution can only be on the form of a "bounty" or "buy me a big and tasty cofea with biscuits".
The question I'm asking myself is whether this should go to some large plug-in like pods (that do not get any more funding from automatic) or almost abandoned one that I see as gems like anthologize.


 
Back to my use case, with this question directly related to #6, I had basically built something in the same vein than co-author, with pods and bi-directional relationship. The need to use taxonomies rather than custom port type pushed me to extend my research, leading to theses questions, and to the discovery of [shadow taxonomies](https://github.com/mrbobbybryant/shadow-taxonomy). 
I now have a fully features system that do not need co-author plus at all, nor any extra features on CiviCRM-ACF integration.
The down side I see it that contact data are fully stored in CiviCRM tables, partially duplicated in Contact custom post types, and again in a Contact-Tax shadow taxonomy


Maybe this research and use case might help someone having the similar need as I had :)

Cheers

**Comment by christianwach** [comment]
Closing because I am archiving this repo in favour of [CiviCRM Profile Sync](https://github.com/christianwach/civicrm-wp-profile-sync).
