### ISSUE TITLE
Bidirectional synk is ok, but contact must be created in Civi ? 

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#8]
Hi, 

I'm facing un unexpexted behaviour, I wouldn't bet this is a bug introduced in recent updates, but yet I'm a bit puzzled.

Basically if I create a contact in Civi, it creates its counter part in wp, and I can update it on any side, the change are ported, excellent !

But if I create a post in wp, for the right custom post, there is no CiviACF integration metabox, and the contact is not created in Civi ! 

The plugin documentation, suggest otherwise

> 
> CiviCRM Contact Types and WordPress Custom Post Types
> 
> To link these together, in CiviCRM go to Administer —> Customize Data and Screens —> Contact Types and edit a Contact Type. You will see a dropdown that allows you to choose a WordPress Post Type to link to the Contact Type you are editing. Choose one and save the Contact Type.
> 
> From now on, each time you create a Contact of the Contact Type that you have linked, a new WordPress Post will be created. The "Display Name" of the Contact will become the WordPress Post Title. And - in the reverse direction - **each time you create a WordPress Post which is of the Post Type you have linked to a Contact Type, a new Contact will be created** with their "Display Name" set to the Title of the new Post

I tried to disable all plug-in but mandatory ones, namely ACF, Civi, ACF-CiviIntegration, and Pods, as I created my CPT with it.

I also tried to revert to 0.6.4

No changes.

Honestly I'm not sure it ever worked the wp->Civi way on my installs, but It may have, I would say probably had, but not sure

Do you have any clues where the issue might be coming from ? 

Thank's in advance

This metabox do not apear in wp admin when I add a post which post type is indeed synced with civi 
![Capture du 2020-07-16 15-28-33](https://user-images.githubusercontent.com/23659411/87676659-2ab9a080-c779-11ea-9367-055b681cd2ce.png)

**Comment by christianwach** [comment]
@jbonlinea Are you on the latest version 0.7.2? Are you adding a title to the WordPress Post?

**Comment by jbonlinea** [comment]
yes, 

I'm on master branch, also tried 0.7.1, 0.7.0, 0.6.3...

I'm adding a title indeed, be I assume the issue precede this point as right in the editor there is no metabox, event before first save...

When the contact is created in Civi the metabox is here

**Comment by christianwach** [comment]
@jbonlinea There has to be a synced Contact for the Metabox to appear. What would it show otherwise? :-)

**Comment by jbonlinea** [comment]
> @jbonlinea There has to be a synced Contact for the Metabox to appear. What would it show otherwise? :-)

good point, but the fact is event after post creation, there are no metabox in the post editor, no CiviCRM link in the post list, and obviously no CiviContact

**Comment by christianwach** [comment]
Try pulling the latest commit and see it works for you.

**Comment by jbonlinea** [comment]
yes I'm using the master branch already ?!

**Comment by christianwach** [comment]
I added a commit about 3 mins ago.

Also, don't forget the filter here:

https://github.com/christianwach/civicrm-acf-integration/issues/3#issuecomment-649522420

**Comment by jbonlinea** [comment]
...

no luck, but I got details 

if I create a contact in Civi, the post is not created, but if I edit this contact, then the post is created.

if I create a post in wp, the contact is not creatd, and if I edit the post, the contact is still not created


ACF 5.8.12
Civi 5.26.2
ACF-Civi - last master, 0.7.2, 0.7.1, 0.7, 0.6.4... still the same
Pods 2.7.21, or 2.7.20.1 or 2.7.18.1

**Comment by christianwach** [comment]
@jbonlinea I can't repeat this with ACF, CiviCRM and this plugin. Could it be that Pods is interfering? It's really hard to assess without having a setup exactly like yours. Is it a dev site that you could give me access to? If so, let's continue via email - you can reach me at needle@haystack.co.uk

**Comment by jbonlinea** [comment]
Small follow up for the records (and anyone facing the issue above)

after some debugging done by @christianwach it apears that the issue rise from the use of the plug-in with contact of type organization

it breaks the functioning of both contact type "organisation" and "individuals", once you disable sync with organisation, the functionality is back for individuals.

a fix should be "posted shortly" ! 

:+1: for the excellent work

**Comment by christianwach** [comment]
Should be fixed in [0.7.2](https://github.com/christianwach/civicrm-acf-integration/releases/tag/0.7.2).

**Comment by jbonlinea** [comment]
It is indeed fixed ! since 0.7.2 :)
