### ISSUE TITLE
Sync Wp-Terms with Civi-Group : ok for groups but not dynamic groups

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#9]
Hi Cristian, 

I recently did some quite extensive test of the functionality which asign a Wp-Term to a post when it's synced contact in Civi is associated to a group. 

It work's very well and it's quite a smart way to bring Civi Group into wp machiery ! 

---

Nevetheless, as great and empowering as this this plug-in is, insanely, big big thank's again, I wish I could sync wp-terms with dynamic group, in a way or an other.

It seems not to be doable at the moment, as dynamic groups are not listed in the term parameters.
I thus tried a workaround, nest a dynamic group into a regular Civi group, the later being tied to a wp-term. The members of the dynamic group are visible in its Civi parent group, but the term is still (sadly) not assigned to the posts, while it do not break the functionality.

---

The use case I have in mind is to use (certain) Civi Relationships to set and automatically maintain (dynamic) group, and reflect this on wp front end thank's to the synced contacts :)

At first look, this seems to be a useful feature, but I may not address the issue in the right way ?!

The only other workaround I could think of would be to to create ACF Civi-relationship field for these type of relationship, which will enable me to distinguish my post based on this criteria, and assign them term programatically (terms may be linked or not to a group)

---

I understand that it may not be doable, simply or at all, for various reasons, but I wanted to share this with you.

Again thank's for this great plug-in ! 

Cheers

**Comment by christianwach** [comment]
> I wish I could sync wp-terms with dynamic group, in a way or an other

@jbonlinea Smart Groups aren't really Groups at all - they are better described as "saved searches". Since they are not "entities" as such, I don't think they will ever be synced by this plugin. You could use CiviRules to dynamically add/remove Contacts to/from a static Group instead.

**Comment by jbonlinea** [comment]
Hi Christian 

Thank's for your quick reply !

Indeed, smart groups aren't proper Civi groups, I knew it, once, but forgot it. It reflect that I was addressing the question from a user standpoint and not a development one. 

Civi rules is indeed a great way to address this need. Built-in Civi, so implementation is simple, efficient, scalable and it keeps the customization and maintenance needs where they are !

Although I have never used/needed Civi-Rule yet, I feel dumb I didn't think about it, but glad if this topic may provide use-guidance for some others.

Many thank's for the tip

Cheers

**Comment by christianwach** [comment]
@jbonlinea I hope the CiviRules approach works for you 👍
